name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests"
        # Run your tests here
        # ...
        
    - name: Install dependencies
      run: |
       npm install @octokit/rest

    - name: Report status to Github
      uses: actions/github-script@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        script: |
          npm install @octokit/rest
           npm install @octokit/rest
          STATUS_CONTEXT='continuous-integration/your-context'
          STATE='success'
          DESCRIPTION='Your tests passed'
          TARGET_URL='https://example.com/status'
          
          npx octokit-repos-create-commit-status \
            --owner "${GITHUB_REPOSITORY%/*}" \
            --repo "${GITHUB_REPOSITORY#*/}" \
            --sha "$GITHUB_SHA" \
            --state "$STATE" \
            --description "$DESCRIPTION" \
            --target-url "$TARGET_URL" \
            --context "$STATUS_CONTEXT"




