name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests"
        # Run your tests here
        # ...
        
    - name: Install dependencies
      run: |
       npm install @octokit/rest

    - name: Report status to Github
      uses: actions/github-script@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        script: |
          npm install @octokit/rest
          const statusContext = 'continuous-integration/your-context';
          const state = 'success';
          const description = 'Your tests passed';
          const target_url = 'https://example.com/status';
          
          const octokit = require('@octokit/rest');
          const client = new octokit({ auth: `token ${process.env.GITHUB_TOKEN}` });
          
           client.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: state,
            description: description,
            target_url: target_url,
            context: statusContext
          });




