name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        echo "Running tests"
        # Run your tests here
        # ...
        
    - name: Install dependencies
      run: |
       npm install @octokit/rest

    - name: Status Create Action
      uses: hkusu/status-create-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sha: ${{ github.sha }}
        state: success # specify 'error', 'failure', 'pending', or 'success'
        target-url: http://ci.example.com # default: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        description: status desc
        context: My Workflow # default: '${{ github.workflow }}'






